---
- name: Install deps
  yum:
    name:
      - policycoreutils-python
      - selinux-policy-devel
    state: present
  when: ansible_distribution == 'CentOS'

- name: Check enabled SELinux modules
  shell: semanage module -l
  register: enabled_modules
  when: ansible_distribution == 'CentOS'

- name: Copy dontmanage_selinux policy
  copy: src=dontmanage_selinux.te dest=/root/dontmanage_selinux.te
  register: dest_dontmanage_selinux_te
  when: ansible_distribution == 'CentOS'

- name: Compile dontmanage_selinux policy
  shell: "make -f /usr/share/selinux/devel/Makefile dontmanage_selinux.pp && semodule -i dontmanage_selinux.pp"
  args:
    chdir: /root/
  when: "ansible_distribution == 'CentOS' and enabled_modules.stdout.find('dontmanage_selinux') == -1 or dest_dontmanage_selinux_te.changed"
...